-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 20:04:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`place` (
  `idplace` INT NOT NULL,
  PRIMARY KEY (`idplace`),
  INDEX `latitude` () VISIBLE,
  INDEX `longtitude` () VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`apprentice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`apprentice` (
  `idapprentice` INT NOT NULL,
  `place_idplace` INT NOT NULL,
  PRIMARY KEY (`idapprentice`),
  INDEX `prename` () INVISIBLE,
  INDEX `lastname` () VISIBLE,
  INDEX `fk_apprentice_place_idx` (`place_idplace` ASC) VISIBLE,
  CONSTRAINT `fk_apprentice_place`
    FOREIGN KEY (`place_idplace`)
    REFERENCES `test`.`place` (`idplace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
